cpk-core/test-src/pt/webdetails/cpk/testUtils/UserContentAccessForTesting.java

[CDE-442]: fixed mock broken by change in cpf IRWAccess interface

---

build-res/subfloor.xml
cpk-core/test-resources/cpkSol/build-res/subfloor.xml
cpk-pentaho/test-resources/repository/system/cpkSol/build-res/subfloor.xml
cpk-pentaho5/test-resources/repository/system/cpkSol/build-res/subfloor.xml

Merge of master into future-develop

Auto-Merge refreshing development branch

---

cpk-pentaho5/ivy.xml

[CLEANUP] - Updating cpf version due to artefact cleanup

---

cpk-core/test-resources/cpkSol/endpoints/kettle/evaluate-result-rows.kjb

- Cherry picked from 6.0 branch.

[CLEANUP] - Simplified Job that was breaking unit test

---

cpk-core/src/pt/webdetails/cpk/CpkEngine.java
cpk-pentaho/src/pt/webdetails/cpk/sitemap/Link.java
cpk-pentaho5/src/pt/webdetails/cpk/sitemap/Link.java

@pamval, @mbatchelor, @tgf, 
the PR should be merged not earlier than: webdetails/cpf#99
Thanks.

[PPP-3506] - XXE Security Vulnerability in xml parsers

---

cpk-core/ivy.xml
cpk-core/src/pt/webdetails/cpk/CpkEngine.java
cpk-core/src/pt/webdetails/cpk/utils/CorsUtil.java
cpk-pentaho5/src/pt/webdetails/cpk/CpkApi.java

@pamval @mbatchelor please review

[CDA-211]-Implement a whitelist for CORS

---

cpk-core/ivy.xml

[BACKLOG-13115] GAV fix for kettle-json-plugin

---

cpk-core/ivy.xml

DO NOT MERGE prior to merge of kettle mavenization!

[BACKLOG-12995] update pdi plugins groupId

---

cpk-core/ivy.xml

@diogofscmariano review and merge please

[TEST] - Fixing test due to http client upgrade

---

README.md
build-res/subfloor.xml
cpk-core/test-resources/cpkSol/README.md
cpk-core/test-resources/cpkSol/build-res/subfloor.xml
cpk-pentaho/test-resources/repository/system/cpkSol/README.md
cpk-pentaho/test-resources/repository/system/cpkSol/build-res/subfloor.xml
cpk-pentaho5/test-resources/repository/system/cpkSol/README.md
cpk-pentaho5/test-resources/repository/system/cpkSol/build-res/subfloor.xml

WARNING!  FOR MERGE BY PROCESS ONLY PLEASE!

[ENGOPS-3650] change Pentaho to Hitachi Vantara and update copyright date

---

pentaho5/pom.xml
pentaho5/src/main/java/pt/webdetails/cpk/InterPluginBroker.java
pentaho5/src/test/java/pt/webdetails/cpk/InterPluginBrokerTest.java
pom.xml

@webdetails/millenniumfalcon please review

[BACKLOG-23575] Pentaho App Builder is broken due to invalid bean id call

---

pentaho5/pom.xml
pentaho5/src/main/java/pt/webdetails/cpk/InterPluginBroker.java
pentaho5/src/test/java/pt/webdetails/cpk/InterPluginBrokerTest.java
pom.xml

@webdetails/millenniumfalcon @pamval please review.

[BACKLOG-24379] Pentaho App Builder is not working in 8.1 GA

---

core/pom.xml
pentaho5/pom.xml
pom.xml

This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo

[PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

---

core/pom.xml
pom.xml

[BACKLOG-27566] Centralize SLF4J dependency

---

core/src/main/java/pt/webdetails/cpk/elements/impl/KettleJobElement.java
core/src/main/java/pt/webdetails/cpk/elements/impl/KettleTransformationElement.java

@andreramos89 
@bcostahitachivantara 
@smmribeiro 
@dcleao

BACKLOG-35795 - Error while creating a plugin using Sparkl

---

core/src/test/resources/cpkSol/build.xml
pentaho5/src/test/resources/repository/system/cpkSol/build.xml

[PPP-4747] -Vulnerable Component :batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747] -Vulnerable Component :batik-1.19

---

core/pom.xml
pentaho5/pom.xml
pentaho5/src/main/java/pt/webdetails/cpk/CpkApi.java
pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpHeadersForTesting.java
pom.xml

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x
[BACKLOG-41601]: https://hv-eng.atlassian.net/browse/BACKLOG-41601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41601]-Upgrade sun jersey from 1.x to glassfish jersey 2.x

---

core/pom.xml
core/src/main/java/pt/webdetails/cpk/CpkCoreService.java
core/src/main/java/pt/webdetails/cpk/elements/impl/KettleElement.java
core/src/main/java/pt/webdetails/cpk/elements/impl/KettleElementHelper.java
core/src/main/java/pt/webdetails/cpk/elements/impl/kettleoutputs/KettleOutput.java
core/src/main/java/pt/webdetails/cpk/elements/impl/kettleoutputs/ResultFilesKettleOutput.java
core/src/main/java/pt/webdetails/cpk/security/IAccessControl.java
core/src/main/java/pt/webdetails/cpk/utils/CpkUtils.java
core/src/test/java/pt/webdetails/cpk/CpkCoreKettleElementTest.java
core/src/test/java/pt/webdetails/cpk/CpkCoreServiceTest.java
core/src/test/java/pt/webdetails/cpk/KettleElementHelperTest.java
core/src/test/java/pt/webdetails/cpk/testUtils/CpkEnvironmentForTesting.java
core/src/test/java/pt/webdetails/cpk/testUtils/HttpServletResponseForTesting.java
core/src/test/java/pt/webdetails/cpk/testUtils/PluginUtilsForTesting.java
core/src/test/java/pt/webdetails/cpk/utils/CpkUtilsTest.java
pentaho5/pom.xml
pentaho5/src/main/java/pt/webdetails/cpk/CpkApi.java
pentaho5/src/main/java/pt/webdetails/cpk/elements/impl/DashboardElement.java
pentaho5/src/main/java/pt/webdetails/cpk/security/AccessControl.java
pentaho5/src/test/java/pt/webdetails/cpk/CpkApiTest.java
pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpHeadersForTesting.java
pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpServletRequestForTesting.java
pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpServletResponseForTesting.java
pom.xml

[BACKLOG-42742]-Upgrading cpk from Java EE to Jakarta EE
[BACKLOG-42742]: https://hv-eng.atlassian.net/browse/BACKLOG-42742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42742]-Upgrading cpk from Java EE to Jakarta EE

---

core/pom.xml
core/src/main/java/pt/webdetails/cpk/CpkEngine.java
core/src/main/java/pt/webdetails/cpk/cache/EHCache.java
core/src/main/java/pt/webdetails/cpk/cache/ICache.java
core/src/main/java/pt/webdetails/cpk/elements/impl/KettleElement.java
core/src/main/resources/ehcache.xml
core/src/test/java/pt/webdetails/cpk/CpkCoreKettleElementTest.java
core/src/test/java/pt/webdetails/cpk/CpkCoreServiceTest.java
core/src/test/java/pt/webdetails/cpk/KettleElementHelperTest.java
core/src/test/java/pt/webdetails/cpk/testUtils/HttpServletResponseForTesting.java
pentaho5/pom.xml
pentaho5/src/test/java/pt/webdetails/cpk/CpkApiTest.java
pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpServletResponseForTesting.java
pom.xml

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

---

pentaho5/src/test/java/pt/webdetails/cpk/testUtils/HttpHeadersForTesting.java

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
